[project]

name = "SECURITY BOT V8 NEXT GEN"

description = "SECURITY BOT V8 NEXT GEN FOR TELEGRAM"

[env]

BOT_TOKEN = "your_bot_token_here"

[build]

command = "pip install -r requirements.txt"

[deploy]

start = "python mybot.py"